export default {
    titolo: "Linux Lab",
    sottotitolo: "Linux Core — from zero to server administration",

    // tracks (the lab family, since 2026-08-25)
    percorsiTitolo: "The tracks",
    percorsiCore: "<strong>Linux Core</strong> — this site: from zero to server administration. Chapters 1–16 in the browser, 17–22 on the local lab.",
    percorsiSystems: "<strong>Linux Systems</strong> — boot, kernel, disks, recovery on real virtual machines. Ready: <a href='https://github.com/manzolo/qlab-plugin-systems-lab' target='_blank' rel='noopener'>qlab plugin</a> (8 chapters).",
    percorsiContainer: "<strong>Container Lab</strong> — from namespaces to a safely run multi-container service. Ready: <a href='https://github.com/manzolo/qlab-plugin-container-lab' target='_blank' rel='noopener'>qlab plugin</a> (11 chapters).",
    tocLegenda: "💻 = runs on your computer (Docker required) · ⚠️ = uses a --privileged container, the chapter explains why",
    tocPrivilegiato: "This chapter uses a --privileged container: the reason and the safeguards are stated in the chapter.",
    navIntro: "Basics",
    navQuaderno: "Notebook",
    navIndice: "Chapters",
    depthBase: "BASE",
    depthPro: "PRO",
    depthTitle: "PRO adds how it works underneath and what breaks",

    capPrec: "← Previous",
    capSucc: "Next →",
    capDi: "Chapter {0} of {1}",
    inLavorazione: "in progress",
    prerequisito: "This chapter assumes chapter {0}. If that means nothing to you, do it first.",
    vaiA: "go",

    labTitolo: "Lab",
    labScarico: "Downloading the machine… {0}%",
    labAvvio: "Booting Linux…",
    labPronta: "Machine ready",
    labPreparazione: "Preparing the exercise… terminal paused",
    labErrore: "Image not built. See lab/README.md: <code>make -C lab all</code>",
    labReimposta: "Reset the machine",
    labReimpostaTitle: "Puts the machine back to its initial state. Use it without fear.",
    labRicomincia: "Restart the exercise",
    labNuovoMondo: "New world",
    labNuovoMondoTitle: "Same exercise, different numbers. It is the best revision there is.",
    labApri: "Open the terminal",
    labChiudi: "Close",

    tipoStato: "state",
    tipoRisposta: "answer",
    tipoMetodo: "method",
    comeConsegnare: "Hand it in from the terminal: <code>lab answer VALUE</code>.",
    comeConsegnareBtn: "Type it in the terminal",
    labReimpostaAnnullo: "machine reset: the in-flight request was cancelled",
    basiStoria: "Where it comes from",
    basiImmagine: "The mental image",
    basiMeccanismo: "The mechanism",
    basiComandi: "This chapter's commands, with their traps",
    basiLab: "How the lab works →",
    attrezzi: "Tools on loan",
    attrezziCap: "chapter {0}",
    aiuto: "Help",
    aiutoChiudi: "Close help",
    aiutoVerifica: "What the check will look at",
    aiutoComandi: "This chapter's commands",
    aiutoNota: "The hints are further down and open one at a time: here is the picture, there is the direction.",
    aiutoTipoStato: "The check looks at how the filesystem ended up: the result counts, not the command you used to get there.",
    aiutoTipoRisposta: "Nothing changes here: you look, and hand in the answer with <code>lab answer</code>. The value differs in every world, so it must be read off the machine.",
    aiutoTipoMetodo: "This exercise also looks at <em>how</em> you got there, and says so openly.",
    esercizi: "Exercises",
    esercizio: "Exercise {0}",
    verifica: "Check",
    verificaInCorso: "Checking…",
    superato: "Passed",
    nonAncora: "Not yet",
    suggerimento: "Hint",
    suggerimentoAltro: "Another hint",
    soluzione: "Show the solution",
    cosaHaVisto: "What the machine saw",
    perche: "Why",
    provaQuesto: "Try looking at it this way",
    solPro: "PRO",
    checkPro: "required in PRO only",
    erroreVerifica: "The check did not answer. Try again, or reset the machine.",

    bloccoTrappole: "Where everybody slips",
    bloccoRecap: "Recap",
    bloccoPro: "Under the hood",
    recapComando: "Command",
    recapCosa: "What it is for",
    recapOpzione: "The option you will actually use",

    localeTitolo: "This chapter runs on your own computer",
    localeCopia: "Copy the command",
    localeCopiato: "Copied",
    localeFatto: "I did it",
    localeFattoOk: "Completed ✓",
    localeFattoNota: "The check runs in the container and the site cannot see it: here you tick the box yourself.",
    predizione: "Before you look: what happens?",
    predizioneGiusta: "Exactly.",
    predizioneSbagliata: "Not quite.",
    mostraOutput: "Show what happened",
    passoSucc: "Next step →",

    quadernoTitolo: "Your notebook",
    quadernoVuoto: "Still empty. Every command you meet while solving an exercise ends up here.",
    quadernoEsporta: "Export to Markdown",
    quadernoDa: "from chapter {0}",

    segnala: "Report a problem",
    segnalaTitle: "Opens a GitHub issue pre-filled with chapter, language, lab status and browser.",
    segnalaCorpo: "**What's wrong?**\n\nDescribe here: what you did, what you expected, what happened.\n\n---\n_Data collected by the page (check and correct if needed):_\n\n- Page: {0}\n- Chapter: {1}\n- Language: {2}\n- Lab status: {3}\n- Browser: `{4}`\n",

    chiudi: "Close",
    mobileAvviso: "The terminal needs a real keyboard: on a phone you can read everything, but come back from a computer to practise.",
    introTitolo: "From scratch",
    introInizia: "Got it — on to chapter 1 →",
};
