export default {
    titolo: "Linux Lab",
    sottotitolo: "Linux Core — da zero all'amministrazione di un server",

    // percorsi (la famiglia di lab, dal 2026-08-25)
    percorsiTitolo: "I percorsi",
    percorsiCore: "<strong>Linux Core</strong> — questo sito: da zero all'amministrazione di un server. Capitoli 1–16 nel browser, 17–22 sul laboratorio locale.",
    percorsiSystems: "<strong>Linux Systems</strong> — boot, kernel, dischi, recovery su macchine virtuali vere. Pronto: <a href='https://github.com/manzolo/qlab-plugin-systems-lab' target='_blank' rel='noopener'>plugin qlab</a> (8 capitoli).",
    percorsiContainer: "<strong>Container Lab</strong> — dai namespace a un servizio multi-container sicuro. Pronto: <a href='https://github.com/manzolo/qlab-plugin-container-lab' target='_blank' rel='noopener'>plugin qlab</a> (11 capitoli).",
    tocLegenda: "💻 = si fa sul tuo computer (serve Docker) · ⚠️ = usa un container --privileged, il capitolo spiega perché",
    tocPrivilegiato: "Questo capitolo usa un container --privileged: il perché e le cautele sono dichiarati nel capitolo.",
    navIntro: "Basi",
    navQuaderno: "Quaderno",
    navIndice: "Capitoli",
    depthBase: "BASE",
    depthPro: "PRO",
    depthTitle: "PRO aggiunge il come funziona sotto e cosa si rompe",

    capPrec: "← Precedente",
    capSucc: "Successivo →",
    capDi: "Capitolo {0} di {1}",
    inLavorazione: "in lavorazione",
    prerequisito: "Questo capitolo dà per scontato il capitolo {0}. Se non ti dice niente, fai prima quello.",
    vaiA: "vai",

    // laboratorio
    labTitolo: "Laboratorio",
    labScarico: "Scarico la macchina… {0}%",
    labAvvio: "Avvio Linux…",
    labPronta: "Macchina pronta",
    labPreparazione: "Preparo l'esercizio… terminale in pausa",
    labErrore: "Immagine non compilata. Vedi lab/README.md: <code>make -C lab all</code>",
    labReimposta: "Reimposta la macchina",
    labReimpostaTitle: "Riporta la macchina allo stato iniziale. Usalo senza timore.",
    labRicomincia: "Ricomincia l'esercizio",
    labNuovoMondo: "Nuovo mondo",
    labNuovoMondoTitle: "Stesso esercizio, numeri diversi. È il ripasso migliore che ci sia.",
    labApri: "Apri il terminale",
    labChiudi: "Chiudi",

    // esercizi
    tipoStato: "stato",
    tipoRisposta: "risposta",
    tipoMetodo: "metodo",
    comeConsegnare: "Si consegna nel terminale: <code>lab answer VALORE</code>.",
    comeConsegnareBtn: "Scrivilo nel terminale",
    labReimpostaAnnullo: "macchina reimpostata: la richiesta in corso è stata annullata",
    basiStoria: "Da dove viene",
    basiImmagine: "L'immagine mentale",
    basiMeccanismo: "Il meccanismo",
    basiComandi: "I comandi del capitolo, con le trappole",
    basiLab: "Come funziona il laboratorio →",
    attrezzi: "Attrezzi in prestito",
    attrezziCap: "capitolo {0}",
    aiuto: "Aiuto",
    aiutoChiudi: "Chiudi l'aiuto",
    aiutoVerifica: "Cosa guarderà la verifica",
    aiutoComandi: "I comandi di questo capitolo",
    aiutoNota: "I suggerimenti stanno più sotto, e si aprono uno alla volta: qui c'è il quadro, lì la direzione.",
    aiutoTipoStato: "La verifica guarda com'è finito il filesystem: conta il risultato, non il comando che hai usato per ottenerlo.",
    aiutoTipoRisposta: "Qui non si cambia niente: si guarda e si consegna la risposta con <code>lab answer</code>. Il valore cambia a ogni mondo, quindi va letto sulla macchina.",
    aiutoTipoMetodo: "Questo esercizio guarda anche <em>come</em> ci sei arrivato, e te lo dice apertamente.",
    esercizi: "Esercizi",
    esercizio: "Esercizio {0}",
    verifica: "Verifica",
    verificaInCorso: "Verifico…",
    superato: "Superato",
    nonAncora: "Non ancora",
    suggerimento: "Suggerimento",
    suggerimentoAltro: "Un altro suggerimento",
    soluzione: "Mostra la soluzione",
    cosaHaVisto: "Cosa ha visto la macchina",
    perche: "Perché",
    provaQuesto: "Prova a guardare così",
    solPro: "PRO",
    checkPro: "richiesto solo in PRO",
    erroreVerifica: "La verifica non ha risposto. Riprova, o reimposta la macchina.",

    // blocchi
    bloccoTrappole: "Dove sbagliano tutti",
    bloccoRecap: "Riepilogo",
    bloccoPro: "Sotto il cofano",
    recapComando: "Comando",
    recapCosa: "A cosa serve",
    recapOpzione: "L'opzione che userai davvero",

    // capitoli locali
    localeTitolo: "Questo capitolo si fa sul tuo computer",
    localeCopia: "Copia il comando",
    localeCopiato: "Copiato",
    localeFatto: "L'ho fatto",
    localeFattoOk: "Completato ✓",
    localeFattoNota: "La verifica gira nel container e il sito non la vede: qui il segno lo metti tu.",
    predizione: "Prima di guardare: cosa succede?",
    predizioneGiusta: "Esatto.",
    predizioneSbagliata: "Non proprio.",
    mostraOutput: "Mostra cosa è successo",
    passoSucc: "Passo successivo →",

    // quaderno
    quadernoTitolo: "Il tuo quaderno di bordo",
    quadernoVuoto: "Ancora vuoto. Ogni comando che incontri risolvendo un esercizio finisce qui.",
    quadernoEsporta: "Esporta in Markdown",
    quadernoDa: "dal capitolo {0}",

    // varie
    chiudi: "Chiudi",
    mobileAvviso: "Il terminale ha bisogno di una tastiera vera: da telefono puoi leggere tutto, ma per esercitarti torna dal computer.",
    introTitolo: "Da zero",
    introInizia: "Ho capito — al capitolo 1 →",
};
